# Generated by Django 5.0.6 on 2024-06-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('nutrional_value', models.TextField()),
                ('image', models.ImageField(upload_to='fruit_images/')),
            ],
        ),
    ]
