# Generated by Django 5.0.6 on 2024-06-16 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_delete_fruit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.FloatField()),
                ('fat', models.FloatField()),
                ('sugar', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('protein', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('order', models.CharField(max_length=100)),
                ('genus', models.CharField(max_length=100)),
                ('nutrition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.nutrition')),
            ],
        ),
    ]
